Add Celery to Flask Server
yaptide/app pull request #125
Opened 2021-11-06 23:08 UTC by p1003

2021-11-08 15:22 UTC, p1003 commented
Currently response returns something really strange, and there is a new problem with updated converter which causes throwing an exception in celery task.

2021-11-08 17:18 UTC, grzanka commented on yaptide/simulation_runner/shieldhit_runner.py
> +        conv_parser = get_parser_from_str("dummy")
```suggestion
        conv_parser = get_parser_from_str("shieldhit")
```
https://github.com/yaptide/yaptide/issues/130

In `/sh/demo` route we will still be using "dummy" parser

2021-11-08 17:19 UTC, grzanka commented
@p1003 please rebase again

2021-11-09 09:35 UTC, grzanka commented on .github/workflows/test-run.yml
> +            docker rmi yaptide-flask
Use consistent naming, like `yaptide_flask` and `yaptide_worker`

2021-11-09 12:56 UTC, grzanka commented
@p1003 take a look here:
https://github.com/yaptide/yaptide/pull/131/files
last changes in converter are now merged, rebase at will

2021-11-09 16:36 UTC, grzanka requested changes, later dismissed
see comments

2021-11-09 16:36 UTC, grzanka commented on docker-compose.yml
> +      - .:/usr/src/app
Are you really copying all files inside docker, including test directories ?

2021-11-09 16:36 UTC, grzanka commented on yaptide/examples/call_api_example.py
> +    api_post = 'http://localhost:5000/sh/run'
add type hinting in this method

2021-11-09 16:36 UTC, grzanka commented on yaptide/simulation_runner/shieldhit_runner.py
> +        time.sleep(4)
Why do you need to sleep here ?

2021-11-09 16:36 UTC, grzanka commented on yaptide/simulation_runner/shieldhit_runner.py
> +        time.sleep(20)
Why do you need to sleep here ?

2021-11-09 16:36 UTC, grzanka commented on yaptide/simulation_runner/shieldhit_runner.py
> +                state=states.FAILURE)
```suggestion
            self.update_state(state=states.FAILURE)
```

2021-11-09 16:36 UTC, grzanka commented on yaptide/routes.py
> +        print(response)
```suggestion
```

Avoid printing on screen. Better to use python logger:
https://docs.python.org/3/howto/logging.html

2021-11-09 16:36 UTC, grzanka commented on README.md
> +2. Run Celery with ```$ celery --app yaptide.simulation_runneelery worker -P threads --loglevel=info```
```suggestion
2. Run Celery with ```$ celery --app yaptide.simulation_runner.shieldhit_runner.celery_app worker -P threads --loglevel=info```
```

2021-11-09 16:36 UTC, grzanka commented on README.md
> +curl -i http://localhost:5000/sh/run?task_id=<task_id>
```suggestion
curl -i http://localhost:5000/sh/status?task_id=<task_id>
```

2021-11-09 16:36 UTC, grzanka commented on README.md
> +curl -i "http://localhost:5000/sh/run?task_id=<task_id>"
```suggestion
curl -i "http://localhost:5000/sh/status?task_id=<task_id>"
```

2021-11-09 16:36 UTC, grzanka commented on yaptide/simulation_runner/shieldhit_runner.py
> +        isRunOk = False  # runner_obj.run(settings=settings)
Switch back to running SH12A simulations

2021-11-09 16:36 UTC, grzanka commented on README.md
> +   * * ```$ docker pull redis```
```suggestion
```

Not needed, as `docker run` would call `docker pull` if necessary

2021-11-09 16:36 UTC, grzanka commented on README.md
> +   * If u ran redis with docker you can use the same terminal
```suggestion
   * You can reuse the same terminal, as for redis, as docker sends redis process to the background
```

2021-11-09 16:36 UTC, grzanka commented on Dockerfile
> +ENV PYTHONDONTWRITEBYTECODE 1
```suggestion
# Python should not try to write .pyc bytecode files
ENV PYTHONDONTWRITEBYTECODE 1
```

Why PYTHONDONTWRITEBYTECODE is needed ?

2021-11-09 16:36 UTC, grzanka commented on Dockerfile
> +ENV PYTHONUNBUFFERED 1
```suggestion
# Force the stdout and stderr streams to be unbuffered. This option has no effect on the stdin stream.
ENV PYTHONUNBUFFERED 1
```

Why this is needed ?

2021-11-09 16:36 UTC, grzanka commented on docker-compose.yml
> +      - .:/usr/src/app
Why is it needed at all if base Dockerfile includes already copying requirements and yaptide folders ?

2021-11-09 16:36 UTC, grzanka commented on Dockerfile
> +# CMD ["flask", "run", "--host=0.0.0.0"]
this can be removed
```suggestion
```

2021-11-09 16:36 UTC, grzanka commented on Dockerfile
>  FROM python:3.9-alpine
Take a look here:
https://github.com/yaptide/yaptide/issues/115#issuecomment-964322162

this should speedup testing process

2021-11-09 16:36 UTC, grzanka commented on docker-compose.yml
> +    build: .
Current docker compose file disables ARGS in Dockerfile which are used to copy `shieldhit` binary inside.
You can use following snippet to fix it:

```
    build: 
      context: .
      args:
        SHIELDHIT_PATH: ${SHIELDHIT_PATH}
```

Then you run `docker compose` in the following way:
```
SHIELDHIT_PATH=shield_hit12a_x86_64_demo_gfortran_v0.9.2/bin/shieldhit docker-compose up -d --build
```

2021-11-09 16:56 UTC, p1003 commented on yaptide/simulation_runner/shieldhit_runner.py
> +        time.sleep(4)
To imitate celery running shieldhit (due to converter problems it was unable to run simulation)

2021-11-09 16:57 UTC, p1003 commented on yaptide/simulation_runner/shieldhit_runner.py
> +        time.sleep(20)
To imitate celery running shieldhit (due to converter problems it was unable to run simulation)

2021-11-09 17:01 UTC, grzanka commented on yaptide/simulation_runner/shieldhit_runner.py
> +        time.sleep(20)
But now shieldhit is running well, try it.

2021-11-09 17:01 UTC, grzanka commented on yaptide/simulation_runner/shieldhit_runner.py
> +        time.sleep(4)
Now we have new converter, give it a try

2021-11-09 17:17 UTC, grzanka commented on Dockerfile
>      apk del gcc musl-dev build-base
```suggestion
RUN pip install -r requirements.txt
```

`apk` is not available in `slim` docker images. Moreover its not needed as we will use wheel packages

2021-11-10 16:31 UTC, p1003 commented on yaptide/examples/call_api_example.py
> +    api_post = 'http://localhost:5000/sh/run'
added

2021-11-10 16:40 UTC, grzanka commented on Dockerfile
>  FROM python:3.9-alpine
@p1003 why did you reverted back to `alpine` flavor ?

2021-11-10 17:08 UTC, grzanka commented on yaptide/routes.py
> +        # return json.dumps({"msg": "Sim Error"}), api_status.HTTP_500_INTERNAL_SERVER_ERROR
can we remove it ?

```suggestion
        # if simulation_result:
        #     return json.dumps(simulation_result), api_status.HTTP_200_OK
        # return json.dumps({"msg": "Sim Error"}), api_status.HTTP_500_INTERNAL_SERVER_ERROR
```

2021-11-10 17:39 UTC, p1003 commented on README.md
> +curl -i http://localhost:5000/sh/run?task_id=<task_id>
You a bit wrong

2021-11-10 17:45 UTC, p1003 commented on docker-compose.yml
> +      - .:/usr/src/app
changed

2021-11-11 22:11 UTC, grzanka approved these changes
looks good

2021-11-12 12:12 UTC, merged