S3 downloading/uploading
yaptide/app pull request #421
Opened 2023-05-30 18:33 UTC by lequ0n

2023-05-30 22:49 UTC, lequ0n commented
In current state four different variables separated by spaces are stored in single environmental variable `endpoint, access_key, secret_key, encryption_key = os.environ["YAPTIDE_S3_CONFIG"].split()`
Endpoint, access_key and secret_key are used to connect with s3. Encryption_key is used in encryption.
I wasn't sure where to place `s3_uploader.py` and currently it is in `/yaptide/utils`.

2023-05-31 07:48 UTC, grzanka commented on yaptide/utils/s3_uploader.py
> +    encrypted = fernet.encrypt(original)
I'd rather create a function which encrypts files and gives back on return a string with file contents. Then file saving and deleting can be easily handled by callers

2023-05-31 07:57 UTC, grzanka requested changes

2023-05-31 07:57 UTC, grzanka commented on yaptide/utils/s3_uploader.py
> +def main():
Use click library as in simulators.py to handle command line options

2023-05-31 07:57 UTC, grzanka commented on yaptide/utils/s3_uploader.py
> +        raise Exception("Upload failed:", e.response["Error"]["Message"]) from e
Replace encrypted_file_path with encrypted_file_contents. Use `with tempfile.NamedTemporaryFile() as temp_file:` to create temporary file to store encrypted shieldhit binary which will be afterwards deleted

2023-05-31 07:57 UTC, grzanka commented on yaptide/utils/s3_uploader.py
> +    if "YAPTIDE_S3_CONFIG" not in os.environ:
Move "YAPTIDE_S3_CONFIG" to a module level variable.

2023-05-31 07:57 UTC, grzanka commented on yaptide/utils/s3_uploader.py
> +    endpoint, access_key, secret_key, encryption_key = os.environ["YAPTIDE_S3_CONFIG"].split()
I would create four separate variables for each of items. All of them should be present to proceed with upload

2023-05-31 07:57 UTC, grzanka commented on yaptide/utils/s3_uploader.py
> +    upload_file_to_s3(endpoint, access_key, secret_key, encryption_key, path, bucket)
Command line script could use `dotenv` library to read the enviromental variables or .env file. It should also accept command line options which overwrite the .env/ env variables. See https://click.palletsprojects.com/en/8.1.x/options/#values-from-environment-variables

2023-05-31 20:13 UTC, grzanka commented on yaptide/admin/simulators.py
> +    if not os.path.isfile(kwargs['file']):
Move to pathlib

2023-05-31 20:47 UTC, grzanka commented on yaptide/admin/simulators.py
> +        if not shieldhit_installed:
```suggestion
            shieldhit_downloaded_from_s3 = download_shieldhit_from_s3()
        if not shieldhit_downloaded_from_s3:
```

2023-05-31 20:51 UTC, grzanka commented on yaptide/admin/simulators.py
> +            s3_client.download_fileobj("shieldhit", "shieldhit", temp_file)
Extract bucket_name and key_name to parameters in the `download_shieldhit_from_s3` method with reasonable default values

2023-05-31 20:56 UTC, grzanka commented on yaptide/admin/simulators.py
> +    os.chmod(destination_file_path, 0o700)
```suggestion
    # Decrypt downloaded file
    click.echo("Decrypting downloaded file")
    fernet = Fernet(encryption_key)
    decrypted_data = fernet.decrypt(encrypted_data)
    with open(destination_file_path, "wb") as f:
        f.write(decrypted_data)
    # Permission to execute
    os.chmod(destination_file_path, 0o700)
```

I would move that section entirely inside `with tempfile.TemporaryFile() as temp_file:` construct

2023-05-31 20:57 UTC, grzanka commented on yaptide/admin/simulators.py
> +            s3_client.download_fileobj("shieldhit", "shieldhit", temp_file)
Also use named parameters

2023-06-01 18:48 UTC, grzanka commented
@lequ0n I think its my task to upload the shielhit binary and put proper secrets in the Github repo, I will do it today.

2023-06-01 20:14 UTC, grzanka commented
Setting in `.env` following line:
```
S3_ENCRYPTION_KEY = 'XXXX'
```

gives me:
```
Traceback (most recent call last):
  File "yaptide/admin/simulators.py", line 263, in <module>
    run()
  File "/data/grzanka/workspace/yaptide/venv/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/data/grzanka/workspace/yaptide/venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/data/grzanka/workspace/yaptide/venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/grzanka/workspace/yaptide/venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/grzanka/workspace/yaptide/venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "yaptide/admin/simulators.py", line 258, in upload
    if upload_file_to_s3(kwargs['bucket'], Path(kwargs['file'])):
  File "yaptide/admin/simulators.py", line 186, in upload_file_to_s3
    encrypted_file_contents = encrypt_file(file_path)
  File "yaptide/admin/simulators.py", line 202, in encrypt_file
    fernet = Fernet(encryption_key)
  File "/data/grzanka/workspace/yaptide/venv/lib/python3.8/site-packages/cryptography/fernet.py", line 39, in __init__
    raise ValueError(
ValueError: Fernet key must be 32 url-safe base64-encoded bytes.
```

2023-06-01 20:25 UTC, grzanka commented
Maybe Fernet with password be a better option, see
https://cryptography.io/en/latest/fernet/#using-passwords-with-fernet

2023-06-01 20:39 UTC, grzanka commented
Fix tests, some bucket names seems hardcoded to wrong values:

`>       assert download_shieldhit_from_s3(bucket="shieldhit", key="shieldhit", installation_path=installation_path) is True`

Bucket and key should be extracted from env variables

2023-06-01 21:08 UTC, grzanka commented
![image](https://github.com/yaptide/yaptide/assets/7374733/7ebc0b72-ee82-4d3d-8d40-ab5af1ef8456)
![image](https://github.com/yaptide/yaptide/assets/7374733/18b1c43a-ccc5-446d-9572-e34251739270)

You should now be able to make some tests, the secrets are on Github Actions

2023-06-02 01:13 UTC, lequ0n commented
Right now encryption_key is derived from password and salt. We need additional secrets `S3_ENCRYPTION_PASSWORD`, `S3_ENCRYPTION_SALT` (`S3_ENCRYPTION_KEY` is no longer needed). Also we need more repository variables for testing on both linux and windows. Bucket `S3_SHIELDHIT_BUCKET` may be same for both  but we need separate keys `S3_LINUX_SHIELDHIT_KEY` and `S3_WINDOWS_SHIELDHIT_KEY` for downloading appropriate files (in current yml there are also separate buckets).

2023-06-02 06:14 UTC, grzanka commented
> Right now encryption_key is derived from password and salt. We need additional secrets `S3_ENCRYPTION_PASSWORD`, `S3_ENCRYPTION_SALT` (`S3_ENCRYPTION_KEY` is no longer needed). Also we need more repository variables for testing on both linux and windows. Bucket `S3_SHIELDHIT_BUCKET` may be same for both but we need separate keys `S3_LINUX_SHIELDHIT_KEY` and `S3_WINDOWS_SHIELDHIT_KEY` for downloading appropriate files (in current yml there are also separate buckets).

I will upload necessary keys today.

2023-06-02 06:31 UTC, grzanka commented
At a later stage we could think of using tags and versions in S3 to avoid too many secrets, but this can go in a subsequent PR

2023-06-04 20:53 UTC, grzanka commented
Before merging I need to check if procedure with https://github.com/yaptide/deploy still works

2023-06-05 15:07 UTC, grzanka approved these changes

2023-06-05 15:07 UTC, grzanka commented on yaptide/admin/simulators.py
> +        os.chmod(destination_file_path, 0o700)
Use pathlib

2023-06-05 15:07 UTC, grzanka commented on yaptide/admin/simulators.py
> +        os.chmod(destination_file_path, 0o700)
I think you already have a path like object

2023-06-05 15:07 UTC, grzanka commented on requirements.txt
> +cryptography==40.0.2
Add newline at the end

2023-06-05 15:07 UTC, grzanka commented on tests/test_secrets.py
> +    assert os.environ.get('S3_ENDPOINT') is not None
```suggestion
    assert 'S3_ENDPOINT' in os.environ
```

2023-06-05 15:07 UTC, grzanka commented on yaptide/admin/simulators.py
> +encryption_key = os.getenv('S3_ENCRYPTION_KEY')
I would remove these module level variables and make them a parameters of all respective functions.

Take a look at this not working use case:
```
python yaptide/admin/simulators.py upload --bucket shieldhit-demo --file ./1/shield_hit12a_x86_64_demo_gfortran_v1.0.1/bin/shieldhit --endpoint https://s3.cloud.cyfronet.pl --access_key XXX --secret_key XXX --encryption_key XXXX
Uploading 1/shield_hit12a_x86_64_demo_gfortran_v1.0.1/bin/shieldhit to S3 bucket shieldhit-demo
Endpoint: None
Access key: None
No credentials found. Check your access key and secret key. Unable to locate credentials
```

2023-06-05 15:07 UTC, grzanka commented on yaptide/admin/simulators.py
> +@click.option('--encryption_key', envvar='S3_ENCRYPTION_KEY', default=encryption_key, help='S3 encryption key')
```suggestion
@click.option('--encryption_key', envvar='S3_ENCRYPTION_KEY', default=encryption_key, help='binary encryption key')
```

Fernet has strict rules on how the key should look like (i.e. string that is converted to extactly 32 bytes). Either provide a clear instruction how to generate such key (random selection of letters doesn't work) or swithc to a different approach, i.e. using passwords in Fernet

2023-06-05 15:07 UTC, grzanka commented on .github/workflows/test-run.yml
> +env:
Use secrets only where needed. Making then per-job global variable exposes some security risk, move assignment of secrets to env variables only to the steps which needs them

2023-06-05 15:07 UTC, grzanka commented on .github/workflows/test-run.yml
> +env:
Include secrets in coverage job in this file as well

2023-06-05 15:07 UTC, grzanka commented on yaptide/admin/simulators.py
> +        click.echo("Uploading file.")
Add filename in the click echo message

2023-06-05 15:08 UTC, merged