Added pre-commit use cases in readme
yaptide/app pull request #883
Opened 2024-03-11 08:51 UTC by dudiiiiiiii

2 use cases of pre-commit added to readme. I also thought about moving them to 2 separate tabs as it was suggested on discord regarding windows and linux commands.

2024-03-11 08:58 UTC, grzanka commented
The style looks like Chat-GPT, can you be more compact ? 

For us main usage of pre-commit is to run yapf. Flake8 is not used. Inspect pre-commit config and check readme.
See https://github.com/yaptide/yaptide/blob/master/.pre-commit-config.yaml
There is also check for empty files, to protect us from commiting `.env` with secrets - try that yourselves and describe in readme.

Put more emphasis on reasons why we use something. Describe how to run pre-commit hooks manually. It is also an useful way.

2024-03-11 18:04 UTC, grzanka commented
<img width="894" alt="Screenshot 2024-03-11 at 19 04 20" src="https://github.com/yaptide/yaptide/assets/7374733/19595f09-5254-4500-ad30-3ffd372066f7">

Do we use flake8 ?

2024-03-11 20:41 UTC, dudiiiiiiii commented
Flake8 is configured in poetry but it isn't used so i supose i can delete this part from readme.

2024-03-11 21:08 UTC, grzanka commented
> Flake8 is configured in poetry but it isn't used so i supose i can delete this part from readme.

You can remove config from pyproject.toml as well.

2024-03-11 21:18 UTC, dudiiiiiiii commented
I've seen that flake8 also shows up in setup.cfg file from converter repo and is not used in pre-commit there also. Should i create issue for it?

2024-03-11 21:23 UTC, grzanka commented
> I've seen that flake8 also shows up in setup.cfg file from converter repo and is not used in pre-commit there also. Should i create issue for it?

Good idea

2024-03-13 12:20 UTC, grzanka requested changes

2024-03-13 12:20 UTC, grzanka commented on README.md
> +1. **Commit Changes**: Commit your changes using `git commit`.
What about ide? Vscode

2024-03-15 17:30 UTC, grzanka approved these changes

2024-03-15 17:50 UTC, merged